name: MLflow CI Model

on:
  push:
    branches:
      - main

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest
    environment: Workflow-CI

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python and Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12.9"
        environment-file: MLProject/conda.yaml
        auto-activate-base: false
        activate-environment: mlflow-env
        channels: conda-forge

    - name: Train MLflow Model (Local Tracking)
      run: |
        cd MLProject
        conda run -n mlflow-env mlflow run . --env-manager=local

    - name: Commit and Push Model Artifact to GitHub
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add mlruns/*
        git commit -m 'Update model artifact from MLflow tracking'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Latest MLflow Model Artifact Path
      run: |
        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | sort -r | head -n 1)
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
        echo "Latest model path: $MODEL_PATH"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image from MLflow Model
      run: |
        conda run -n mlflow-env mlflow models build-docker \
          -m ${{ env.MODEL_PATH }} \
          -n padi-forecasting-model

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag padi-forecasting-model:latest ${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest
        docker push ${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest
