name: CI - Model Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Set MLflow Tracking URI for DagsHub
        run: |
          echo "MLFLOW_TRACKING_URI=https://${{ secrets.DAGSHUB_USERNAME }}:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/Silvikusuma04/padi_forecasting.mlflow" >> $GITHUB_ENV
        shell: bash

      - name: Run Model Training with MLflow
        run: |
          python modelling.py
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest .
          docker push ${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest
