name: CI - Model Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          channels: conda-forge

      - name: Install MLflow CLI (jaga-jaga)
        run: pip install mlflow

      - name: Run MLflow Project with Authenticated URI
        env:
          MLFLOW_TRACKING_URI: https://${{ secrets.DAGSHUB_USERNAME }}:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/Silvikusuma04/padi_forecasting.mlflow
        run: |
          mlflow run MLProject --env-manager=local
        shell: bash -l {0}

      - name: Install tools for Docker build
        run: |
          sudo apt-get update && sudo apt-get install -y jq
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          RUN_ID=$(mlflow runs list --experiment-name "Paddy Yield Forecast - Foundational Model" --output json | jq -r '.[0].info.run_id')
          echo "Latest Run ID: $RUN_ID"

          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/random_forest_model" \
            --name "${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model"

          docker push "${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest"
        env:
          MLFLOW_TRACKING_URI: https://${{ secrets.DAGSHUB_USERNAME }}:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/Silvikusuma04/padi_forecasting.mlflow
        shell: bash -l {0}
