name: CI - Model Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python and Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12.9"
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow-env
          channels: conda-forge

      - name: Set Environment Variables for MLflow
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/Silvikusuma04/padi_forecasting.mlflow" >> $GITHUB_ENV
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      - name: Run MLflow Project to Train Model
        run: |
          cd MLProject
          mlflow run .
        shell: bash -l {0}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image (Advanced)
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          
          RUN_ID=$(mlflow runs list --experiment-name "Paddy Yield Forecast - Foundational Model" --query "tags.mlflow.source.type='PROJECT'" -o json | jq -r '.[0].info.run_id')
          echo "Latest Run ID is $RUN_ID"
          
          mlflow models build-docker --model-uri "runs:/$RUN_ID/random_forest_model" --name "${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model"
          
          docker push ${{ secrets.USERNAME_DOCKER }}/padi-forecasting-model:latest
        shell: bash -l {0}